[package]
name = "fdllm"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "fdllm"
path = "src/main.rs"

[dependencies]
copypasta = "0.10"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
